---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/cardiecr/public_html/
    # - /bin/cp -R .vscode $DEPLOYPATH
    # - /bin/cp -R public $DEPLOYPATH
    # - /bin/cp -R src $DEPLOYPATH
    - /bin/npm i
    - /bin/npm run build
    - /bin/cp -R build $DEPLOYPATH

