version: '3.4'

services:
  stegracavalise:
    image: stegracavalise
    build:
      context: stegraca-valise
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PUID: 1000
      PGID: 1001
    ports:
      - 3000:3000
    volumes:
    - "/home/dad/.docker/stegraca-valise:/workspaces:cached"
    command: /bin/sh -c "while sleep 1000; do :; done"